### ISSUE TITLE
1 and 20

### ISSUE THREAD

**Issue by GildedHonour** [nash-io/base58check#2]
Where do 1 and 20 come from?

https://github.com/nash-io/base58check/blob/f4079c63a6bd1ea79f51fe91fb0533cabe72b506/lib/base_58_check/base_58_check.ex#L40

**Comment by GildedHonour** [comment]
@all @adrienmo  @localhuman  @notdanilo  @adrienmo  up

**Comment by adrienmo** [comment]
Hi @GildedHonour 

After running `Base58Zero.decode()`, the binary you are getting is the following:
`prefix <> payload <> checksum`

The prefix is 1 byte, the payload is 20 bytes, hence we are using `binary_part(1, 20)` to retrieve the payload only

**Comment by GildedHonour** [comment]
@adrienmo 

When I was trying to parse a response from an API that works with TRON the blockchain,  I found out that this library wasn't working properly because of these hard-coded values: 1 and 20

I forked it, changed 1 to 0, and 20 to 21 and it began to work. 

```
|> binary_part(0, 21)

```
I found that out by comparing a result of this library from the one of a library in Python. The one of this library was 2 bytes shorted and therefore overall my application wouldn't  work correctly.

Where do those `1` of prefix and `20` bytes of length come from? I haven't found any hint in any source out there.

**Comment by adrienmo** [comment]
@GildedHonour 
I am not sure what you are trying to do. This library is for the bitcoin implementation, I have no idea what is TRON doing.
You might want to use the function `Base58Check.decode58zero!` that is not removing the address prefix and the checksum.

The list of bitcoin prefix is here: https://en.bitcoin.it/wiki/List_of_address_prefixes
A tool to play with the prefix and checksum is here: https://learnmeabitcoin.com/technical/address
